# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Chemin vers la clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # Chemin vers la clé publique
    token_ttl: 3600
api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: security.credentials.password