nelmio_api_doc:
    documentation:
        info:
            title: Lendora Librairie
            description: This is an awesome app!
            version: 1.0.0
            x-build: #CommitHash
        security:
            - Bearer: []
        paths:
            /api/authors:
                get:
                    tags:
                        - Authors
                    summary: Get all authors.
                    responses:
                        "200":
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                id:
                                                    type: integer
                                                name:
                                                    type: string
                                                lastName:
                                                    type: string
                                                birthday:
                                                    type: date
                                                biography:
                                                    type: string
                post:
                    tags:
                        - Author
                    summary: Create a new author.
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        name:
                                            type: string
                                        lastName:
                                            type: string
                                        birthday:
                                            type: date
                                        biography:
                                            type: string
                    responses:
                        "201":
                            description: Created
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                            name:
                                                type: string
                                            lastName:
                                                type: string
                                            birthday:
                                                type: date
                                            biography:
                                                type: string
                        "400":
                            description: Invalid JSON.
                security: [ ]
            /api/authors/{id}:
                get:
                    tags:
                        - Author
                    summary: Get author by id
                    parameters:
                        - name: id
                          in: path
                          required: true
                          schema:
                              type: integer
                    responses:
                        "200":
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                                example: 1
                                            name:
                                                type: string
                                                example: "John"
                                            lastName:
                                                type: string
                                                example: "Doe"
                                            birthday:
                                                type: string
                                                format: date
                                                example: "1980-01-01"
                                            biography:
                                                type: string
                                                example: "Author of many great books."
                        "404":
                            description: Not found
            /api/books:
                get:
                    tags:
                        - Books
                    summary: Get all authors.
                    responses:
                        "200":
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                title:
                                                    type: string
                                                releaseDate:
                                                    type: date
                post:
                    tags:
                        - Categories
                    summary: Create a new category.

                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        name:
                                            type: string
                    responses:
                        "201":
                            description: Created
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                            name:
                                                type: string
                        "400":
                            description: Invalid JSON.
            /api/users:
                get:
                    tags:
                        - Users
                    summary: Get all users.
                    responses:
                        "200":
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                id:
                                                    type: integer
                                                email:
                                                    type: string
                                                roles:
                                                    type: array
                                                    items:
                                                        type: string
                post:
                    tags:
                        - Users
                    summary: Create a new user.
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                        password:
                                            type: string
                                        roles:
                                            type: array
                                            items:
                                                type: string
                    responses:
                        "201":
                            description: Created
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                            email:
                                                type: string
                                            roles:
                                                type: array
                                                items:
                                                    type: string
                        "400":
                            description: Invalid JSON.
            /api/users/{id}:
                get:
                    tags:
                        - Users
                    summary: Get a user by id.
                    parameters:
                        - name: id
                          in: path
                          required: true
                          schema:
                              type: integer
                    responses:
                        "200":
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                            email:
                                                type: string
                                            roles:
                                                type: array
                                                items:
                                                    type: string
                        "404":
                            description: Not found

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)
        host_patterns:
            - ^api\.
